# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VerbNet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Synsets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(max_length=30)),
                ('aspect', models.CharField(max_length=30)),
                ('definition', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
